package zombieapocalypse.model.mapcreation;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import zombieapocalypse.model.cell.Cell;
import zombieapocalypse.model.cell.EmptyCell;
import zombieapocalypse.model.cell.HotelRoomCell;
import zombieapocalypse.model.cell.PharmacyRoomCell;
import zombieapocalypse.model.cell.RoomCell;
import zombieapocalypse.model.cell.StreetCell;
import zombieapocalypse.model.structure.*;

/**
 * Represents a map generator in the game.
 */
public class MapGenerator {
    /**
     * The map generated by this MapGenerator.
     */
    protected Map map;

    /**
     * Constructs a MapGenerator with the specified width and height for the map.
     * 
     * @param width  The width of the map to be generated
     * @param height The height of the map to be generated
     */
    public MapGenerator(int width, int height) {
        this.map = new Map(width, height);
    }

    /**
     * Gets the generated map.
     * 
     * @return The generated map
     */
    public Map getMap() {
        return this.map;
    }

    /**
     * Adds a column of StreetCells at the specified index.
     * 
     * @param street The street to add
     * @param index  The column index to add the Street
     */
    public void addStreetX(Street street, int index) {
        int i = 0;
        while (i < this.map.getWidth()) {
            this.map.setCell(i, index, new StreetCell("street", street));
            i++;
        }
    }

    /**
     * Adds a row of StreetCells at the specified index.
     * 
     * @param street The street to add
     * @param index  The row index to add the Street
     */
    public void addStreetY(Street street, int index) {
        int i = 0;
        while (i < this.map.getHeight()) {
            this.map.setCell(index, i, new StreetCell("street", street));
            i++;
        }
    }

    /**
     * Returns a list of possible columns for a Street, empty list if not possible.
     * 
     * @return List of possible columns for a Street
     */
    public List<Integer> canBeSplitX() {
        List<Integer> res = new ArrayList<>();
        int temp = 0;
        for (int i = 0; i < this.map.getHeight(); i++) {
            if (this.map.getCell(0, i) instanceof EmptyCell) {
                temp++;
                if (temp > 4) {
                    res.add(i - 2);
                }
            } else {
                temp = 0;
            }
        }
        return res;
    }

    /**
     * Returns a list of possible rows for a Street, empty list if not possible.
     * 
     * @return List of possible rows for a Street
     */
    public List<Integer> canBeSplitY() {
        List<Integer> res = new ArrayList<>();
        int temp = 0;
        for (int i = 0; i < this.map.getWidth(); i++) {
            if (this.map.getCell(i, 0) instanceof EmptyCell) {
                temp++;
                if (temp > 4) {
                    res.add(i - 2);
                }
            } else {
                temp = 0;
            }
        }
        return res;
    }

    /**
     * Adds the Streets to this Map
     */
    public void addStreets() {
        Random random = new Random();
        int i = 0;
        while (canBeSplitX().size() > 0) {
            List<Integer> possibleStreets = canBeSplitX();
            addStreetX(new Street("Street" + Integer.toString(i), false),
                    possibleStreets.get(random.nextInt(possibleStreets.size())));
            i++;
        }
        while (canBeSplitY().size() > 0) {
            List<Integer> possibleStreets = canBeSplitY();
            addStreetY(new Street("Street" + Integer.toString(i), false),
                    possibleStreets.get(random.nextInt(possibleStreets.size())));
            i++;
        }
    }

    /**
     * Sets the main roads to the map.
     */
    public void addMainroads() {
        Random random = new Random();
        int[] mainroads = { 0, 0 };
        while (true) {
            int index = random.nextInt(this.map.getWidth());
            Cell cell = this.map.getCell(index, 0);
            if (cell instanceof StreetCell) {
                mainroads[0] = index;
                StreetCell c = (StreetCell) cell;
                c.getStreet().setIsMainroads(true);
                break;
            }
        }
        while (true) {
            int index = random.nextInt(this.map.getHeight());
            Cell cell = this.map.getCell(0, index);
            if (cell instanceof StreetCell) {
                mainroads[1] = index;
                StreetCell c = (StreetCell) cell;
                c.getStreet().setIsMainroads(true);
                break;
            }
        }
        StreetCell cell = (StreetCell) this.map.getCell(mainroads[0], 0);
        cell.setHasSewer(true);
        this.map.addSewerCell(cell);
        cell = (StreetCell) this.map.getCell(mainroads[0], this.map.getHeight() - 1);
        cell.setHasSewer(true);
        this.map.addSewerCell(cell);
        cell = (StreetCell) this.map.getCell(0, mainroads[1]);
        cell.setHasSewer(true);
        this.map.addSewerCell(cell);
        cell = (StreetCell) this.map.getCell(this.map.getWidth() - 1, mainroads[1]);
        cell.setHasSewer(true);
        this.map.addSewerCell(cell);
        this.map.setMainroads(mainroads[0], mainroads[1]);
    }

    /**
     * Adds the Rooms to this Map
     */
    public void addRooms() {
        for (int i = 0; i < this.map.getWidth(); i++) {
            for (int j = 0; j < this.map.getHeight(); j++) {
                if (this.map.getCell(i, j) instanceof EmptyCell) {
                    this.map.setCell(i, j, new RoomCell("Room" + " " + i + " " + j));
                }
            }
        }
    }

    /**
     * Adds a random cell to the map.
     * 
     * @param cell The cell to add
     */
    public void addCellRandom(Cell cell) {
        Random random = new Random();
        while (true) {
            int x = random.nextInt(this.map.getWidth());
            int y = random.nextInt(this.map.getHeight());
            if (this.map.getCell(x, y).getName().substring(0, 4).equals("Room")) {
                this.map.setCell(x, y, cell);
                break;
            }
        }
    }

    /**
     * Adds doors to the rooms on the map.
     */
    public void addDoors() {
        for (int i = 0; i < this.map.getWidth(); i++) {
            for (int j = 0; j < this.map.getHeight(); j++) {
                if (this.map.getCell(i, j) instanceof RoomCell) {
                    RoomCell room = (RoomCell) this.map.getCell(i, j);
                    if (i + 1 != this.map.getWidth()) {
                        room.setDoor(new Door(false, false), 2);
                    }
                    if (j + 1 != this.map.getHeight()) {
                        room.setDoor(new Door(false, false), 1);
                    }
                    if (i > 0 && this.map.getCell(i - 1, j) instanceof RoomCell) {
                        RoomCell topRoom = (RoomCell) this.map.getCell(i - 1, j);
                        List<Door> doors = topRoom.getDoors();
                        room.setDoor(doors.get(2), 0);
                    } else {
                        room.setDoor(new Door(false, false), 0);
                    }
                    if (j > 0 && this.map.getCell(i, j - 1) instanceof RoomCell) {
                        RoomCell leftRoom = (RoomCell) this.map.getCell(i, j - 1);
                        List<Door> doors = leftRoom.getDoors();
                        room.setDoor(doors.get(1), 3);
                    } else {
                        room.setDoor(new Door(false, false), 3);
                    }
                } else {
                    if (i + 1 != this.map.getWidth()) {
                        if (this.map.getCell(i + 1, j) instanceof RoomCell) {
                            RoomCell bottomRoom = (RoomCell) this.map.getCell(i + 1, j);
                            bottomRoom.setDoor(new Door(false, false), 0);
                        }
                    }
                    if (j + 1 != this.map.getHeight()) {
                        if (this.map.getCell(i, j + 1) instanceof RoomCell) {
                            RoomCell rightRoom = (RoomCell) this.map.getCell(i, j + 1);
                            rightRoom.setDoor(new Door(false, false), 3);
                        }
                    }
                }
            }
        }
    }

    /**
     * Overrides the main roads in the map with the same street instance to ensure connectivity.
     */
    public void overrideMainroads() {
        int[] mainroads = this.map.getMainroads();
        Street mainroadX = ((StreetCell) this.map.getCell(mainroads[0], 0)).getStreet();
        Street mainroadY = ((StreetCell) this.map.getCell(0, mainroads[1])).getStreet();
        for (int i = 0; i < this.map.getHeight(); i++) {
            Cell cell = this.map.getCell(mainroads[0], i);
            if (cell instanceof StreetCell) {
                StreetCell streetcell = (StreetCell) cell;
                if (!streetcell.getStreet().equals(mainroadX)) {
                    streetcell.setStreet(mainroadX);
                }
            }
        }
        for (int i = 0; i < this.map.getWidth(); i++) {
            Cell cell = this.map.getCell(i, mainroads[1]);
            if (cell instanceof StreetCell) {
                StreetCell streetcell = (StreetCell) cell;
                if (!streetcell.getStreet().equals(mainroadY)) {
                    streetcell.setStreet(mainroadY);
                }
            }
        }
    }

    /**
     * Generates a map by adding streets, rooms, main roads, doors, and random cells
     * like pharmacies and hotel rooms.
     * 
     * @return The generated map
     */
    public Map generateMap() {
        this.addStreets();
        this.addRooms();
        this.addCellRandom(new PharmacyRoomCell());
        this.addCellRandom(new HotelRoomCell());
        this.addMainroads();
        this.addDoors();
        this.overrideMainroads();
        return this.map;
    }
}
